cars = ["BMW","Thar","Punch"]
print(cars[2])
cars[0]="creta"
print(cars)
cars.append("swift")
print(cars)
cars.insert(1,"verna")
print(cars)
cars.pop(1)
print(cars)
cars.remove("Punch")
print(cars)

list=[10,20,30,40,50,60]
print(list)
list.append(90)
print(list)
list.insert(2,100)
print(list)
list.remove(60)
print(list)
list.pop(4)
print(list)
print(len(list))
list.sort()
print(list)
list.reverse()
print(list)
print(min(list))
print(max(list))
list1 = list.copy()
print(list1)
res = list + list1
print(res)